my_name = input("Enter your name: ")
print("Hello " + my_name + "!")
print("Hello {}!".format(my_name))
print(f"Hello {my_name}!")
print("Hello, %s!" % my_name)
my_age = int(input("Enter your age: "))
print(f"You are  {my_age} years old.")
print("You are %d years old" % my_age)
print("You are {} years old".format(my_age))
print("You are " + my_age + "years old")